export const Questions = [
    {
      images: "./02-soru1_mevsimler.jpg",
      prompt: "Çocuğunuz için balık yağını hangi mevsimlerde kullanmayı düşünüyorsunuz? (Birden fazla seçenek işaretleyebilirsiniz.)",
      optionA: "Kış",
      optionB: "İlkbahar",
      optionC: "Yaz",
      optionD: "Sonbahar",
      optionE: "Her Mevsim",
      asnwer: "optionD",
    },
    {
      images: "./03-soru2_yas.jpg",
      prompt: "Balık yağı takviyesi kullanmasını istediğiniz çocuğunuz kaç yaşında?",
      optionA: "Seçiniz",
      optionB: "12 ve Üstü",
      asnwer: "optionB",
    },
    {
      images: "./04-soru3_cinsiyet.jpg",
      prompt: "Balık yağı takviyesi kullanmasını istediğiniz çocuğunuzun cinsiyeti nedir?",
      optionA: "Kız",
      optionB: "Erkek",
      asnwer: "optionB",
    },
    {
      images: "./05-soru4_ilk_sira.jpg",
      prompt: "Balık yağı tercih ederken ilk sıraya neyi koyarsınız?",
      optionA: "Kolay Kullanım",
      optionB: "Tadı ve Kokusu",
      optionC: "Oksidasyon değerlerinin bozulmaması",
      optionD: "Fiyat",
      optionE: "Güvenilirlik",
      asnwer: "optionD",
    },
    {
      images: "./06-soru5_onceliginiz.jpg",
      prompt: "Şu andaki önceliğiniz nedir?",
      optionA: "Çocuğumun tek bir seferde, ideal doza sahip omega-3 ve D vitamini almasını istiyorum.",
      optionB: "Çocuğumun bağışıklık sistemine destek olabilecek özel bir formüle sahip besin takviyesi arıyorum.",
      optionC: "Çocuğumun günlük beslenmesine destek olması amacıyla vitamin almasını öncelikli olarak önemsiyorum.",
      optionD: "Çocuğumun beyin fonksiyonuna destek olabilecek özel bir formüle sahip besin takviyesi arıyorum.",
      asnwer: "optionD",
    },
  ];